# Navigation
curriculum_title:
  default: Visit the Curriculum
  description: "This text will be displayed in the curriculum navigation item"
curriculum_title_short:
  default: Curriculum
  description: "This is the short version of curriculum title used for mobile devices"
curriculum_src:
  default: https://www.freecodecamp.org/learn
  description: "This the link to related language curriculum"

# Analytics
Google_Tag_Manager:
  default: ""
  description: "Google Tag Manager ID"

# Footer description section
footer_paragraph_1:
  default: "freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit
    organization (United States Federal Tax Identification Number:
    82-0779546)"
  description: "First footer paragraph"
footer_paragraph_2:
  default:
    "Our mission: to help people learn to code for free. We accomplish this
    by creating thousands of videos, articles, and interactive coding
    lessons - all freely available to the public. We also have thousands
    of freeCodeCamp study groups around the world."
  description: "Second footer paragraph"
footer_paragraph_3:
  default: "Donations to freeCodeCamp go toward our education initiatives, and
    help pay for servers, services, and staff."
  description: "Second footer paragraph"
footer_donation_cta:
  default: "You can make a tax-deductible donation here."
  description: "Footer donation paragraph"

# Footer columns section
footer_columns_header:
  default: "Trending Guides"
  description: "Header for footer link columns"
footer_col1_item1_link: "https://www.freecodecamp.org/news/what-is-docker-used-for-a-docker-container-tutorial-for-beginners/"
footer_col1_item1_text: "What is Docker?"
footer_col1_item2_link: "https://www.freecodecamp.org/news/what-is-tcp-ip-layers-and-protocols-explained/"
footer_col1_item2_text: "TCP/IP Model"
footer_col1_item3_link: "https://www.freecodecamp.org/news/rtf-file-what-is-the-rich-text-format/"
footer_col1_item3_text: "RTF File"
footer_col1_item4_link: "https://www.freecodecamp.org/news/css-transition-examples/"
footer_col1_item4_text: "CSS Transition"
footer_col1_item5_link: "https://www.freecodecamp.org/news/how-to-use-instagram-like-a-pro/"
footer_col1_item5_text: "How to Use Instagram?"
footer_col1_item6_link: "https://www.freecodecamp.org/news/mbr-vs-gpt-whats-the-difference-between-an-mbr-partition-and-a-gpt-partition-solved/"
footer_col1_item6_text: "MBR VS GPT"
footer_col1_item7_link: "https://www.freecodecamp.org/news/how-to-format-a-usb-drive-to-fat32-on-windows-10/"
footer_col1_item7_text: "FAT32 Format"
footer_col1_item8_link: "https://www.freecodecamp.org/news/http-error-503-service-unavailable-explained-what-the-503-error-code-means/"
footer_col1_item8_text: "Error 503 Code"
footer_col1_item9_link: "https://www.freecodecamp.org/news/how-to-find-and-edit-a-windows-hosts-file/"
footer_col1_item9_text: "Windows Hosts File"
footer_col1_item10_link: "https://www.freecodecamp.org/news/mobi-to-pdf-how-to-convert-to-and-from-a-mobi-file/"
footer_col1_item10_text: "Mobi to PDF"
footer_col2_item1_link: "https://www.freecodecamp.org/news/what-is-stem-the-meaning-of-an-acronym-youll-hear-a-lot-in-school/"
footer_col2_item1_text: "What is STEM?"
footer_col2_item2_link: "https://www.freecodecamp.org/news/javascript-void-keyword-explained/"
footer_col2_item2_text: "JavaScript Void 0"
footer_col2_item3_link: "https://www.freecodecamp.org/news/sql-delete-row-statement-examples/"
footer_col2_item3_text: "SQL Delete Row"
footer_col2_item4_link: "https://www.freecodecamp.org/news/javascript-string-replace-example-with-regex/"
footer_col2_item4_text: "JavaScript Replace"
footer_col2_item5_link: "https://www.freecodecamp.org/news/python-read-json-file-how-to-load-json-from-a-file-and-parse-dumps/"
footer_col2_item5_text: "Python JSON Parser"
footer_col2_item6_link: "https://www.freecodecamp.org/news/cmd-delete-folder-how-to-remove-files-and-folders-in-windows/"
footer_col2_item6_text: "cmd Delete Folder"
footer_col2_item7_link: "https://www.freecodecamp.org/news/what-is-nfc-near-field-communication-uses-chips-tags-and-readers-explained/"
footer_col2_item7_text: "What is NFC?"
footer_col2_item8_link: "https://www.freecodecamp.org/news/what-is-the-correct-content-type-for-json-request-header-mime-type-explained/"
footer_col2_item8_text: "Content Type JSON"
footer_col2_item9_link: "https://www.freecodecamp.org/news/heic-to-jpg-how-to-convert-images-on-a-mac/"
footer_col2_item9_text: "Convert HEIC to JPG"
footer_col2_item10_link: "https://www.freecodecamp.org/news/generate-random-numbers-java/"
footer_col2_item10_text: "Math Random Java"
footer_col3_item1_link: "https://www.freecodecamp.org/news/how-to-start-a-blog-with-wordpress/"
footer_col3_item1_text: "WordPress for Beginners"
footer_col3_item2_link: "https://www.freecodecamp.org/news/qualitative-vs-quantitative-definition-research-methods-and-data/"
footer_col3_item2_text: "Qualitative VS Quantitative"
footer_col3_item3_link: "https://www.freecodecamp.org/news/javascript-split-string-example/"
footer_col3_item3_text: "JavaScript Split String"
footer_col3_item4_link: "https://www.freecodecamp.org/news/how-to-type-letters-with-accents-on-mac/"
footer_col3_item4_text: "Accented Letters on Mac"
footer_col3_item5_link: "https://www.freecodecamp.org/news/how-to-find-a-windows-10-product-key/"
footer_col3_item5_text: "Windows 10 Product Key"
footer_col3_item6_link: "https://www.freecodecamp.org/news/google-docs-landscape-tutorial-how-to-make-a-google-doc-landscape-orientation/"
footer_col3_item6_text: "Google Docs Landscape"
footer_col3_item7_link: "https://www.freecodecamp.org/news/antimalware-service-executable-what-is-msmpeng-exe-and-why-is-it-running-in-windows-10/"
footer_col3_item7_text: "Antimalware Executable"
footer_col3_item8_link: "https://www.freecodecamp.org/news/windows-10-start-menu-not-working-solved/"
footer_col3_item8_text: "Windows 10 Start Menu"
footer_col3_item9_link: "https://www.freecodecamp.org/news/how-to-open-the-command-prompt-in-windows-10/"
footer_col3_item9_text: "Windows 10 Command Line"
footer_col3_item10_link: "https://www.freecodecamp.org/news/google-account-recovery-change-gmail-password/"
footer_col3_item10_text: "Google Account Recovery"

footer_our_org_header:
  default: "Our Nonprofit"
  description: "Title for organizational links"
footer_about_link: "https://www.freecodecamp.org/news/about/"
footer_about_text: "About"
footer_Alumni_Network_link: "https://www.linkedin.com/school/free-code-camp/people/"
footer_Alumni_Network_text: "Alumni Network"
footer_Open_Source_link: "https://github.com/freeCodeCamp/"
footer_Open_Source_text: "Open Source"
footer_Shop_link: "https://www.freecodecamp.org/shop/"
footer_Shop_text: "Shop"
footer_Support_link: "https://www.freecodecamp.org/news/support/"
footer_Support_text: "Support"
footer_Sponsors_link: "https://www.freecodecamp.org/news/sponsors/"
footer_Sponsors_text: "Sponsors"
footer_Academic_Honesty_link: "https://www.freecodecamp.org/news/academic-honesty-policy/"
footer_Academic_Honesty_text: "Academic Honesty"
footer_Code_of_Conduct_link: "https://www.freecodecamp.org/news/code-of-conduct/"
footer_Code_of_Conduct_text: "Code of Conduct"
footer_Privacy_Policy_link: "https://www.freecodecamp.org/news/privacy-policy/"
footer_Privacy_Policy_text: "Privacy Policy"
footer_Terms_of_Service_link: "https://www.freecodecamp.org/news/terms-of-service/"
footer_Terms_of_Service_text: "Terms of Service"
footer_Copyright_Policy_link: "https://www.freecodecamp.org/news/copyright-policy/"
footer_Copyright_Policy_text: "Copyright Policy"
